---
abstract: 'Display possible merge conflicts between'
author:
  - 'Travis Holton <heytrav@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Git-CheckMergeConflicts
provides:
  App::Git::CheckMergeConflicts:
    file: lib/App/Git/CheckMergeConflicts.pm
    version: 0.01
requires:
  App::gh::Git: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
